[versions]
fabric-loader = "0.16.10"
loom = "1.10.1"
minecraft = "1.21.5"
yarn = "1.21.5+build.1"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "loom" }
